version: '3'

services:
  db:
    container_name: postgres_aseca
    image: postgres:12
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
    volumes:
      - postgdata:/var/lib/postgresql/data

volumes:
  postgdata: {}
